# Generated by Django 5.2.4 on 2025-07-25 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pedidos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_pagamento",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("mercadopago", "Mercado Pago"),
                            ("pix", "PIX"),
                            ("boleto", "Boleto"),
                        ],
                        max_length=20,
                        verbose_name="Gateway de Pagamento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processando", "Processando"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                            ("cancelado", "Cancelado"),
                            ("estornado", "Estornado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ID da Transação"
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Payment Intent ID (Stripe)",
                    ),
                ),
                (
                    "preference_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Preference ID (Mercado Pago)",
                    ),
                ),
                (
                    "cartao_ultimos_digitos",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Últimos 4 Dígitos"
                    ),
                ),
                (
                    "cartao_bandeira",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Bandeira do Cartão"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadados"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_processamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Processamento"
                    ),
                ),
                (
                    "data_confirmacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Confirmação"
                    ),
                ),
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamento",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="LogPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=100, verbose_name="Evento")),
                (
                    "dados",
                    models.JSONField(default=dict, verbose_name="Dados do Evento"),
                ),
                (
                    "data_evento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Evento"
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="pagamentos.pagamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Pagamento",
                "verbose_name_plural": "Logs de Pagamento",
                "ordering": ["-data_evento"],
            },
        ),
    ]
