# Generated by Django 5.2.4 on 2025-08-14 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="forma_pagamento",
            field=models.CharField(
                default="mercado_pago", max_length=20, verbose_name="Forma de Pagamento"
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Payment ID (Mercado Pago)"
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Método de Pagamento"
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="transaction_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor da Transação",
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("mercado_pago", "Mercado Pago"),
                    ("pix", "PIX"),
                    ("boleto", "Boleto"),
                ],
                default="mercado_pago",
                max_length=20,
                verbose_name="Gateway de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagamentos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
    ]
