# Generated by Django 5.2.4 on 2025-07-25 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fornecedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, upload_to="categorias/", verbose_name="Imagem"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "cor",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="Cor (Hex)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "descricao_curta",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Descrição Curta"
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "preco_promocional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço Promocional",
                    ),
                ),
                (
                    "tamanhos_disponiveis",
                    models.JSONField(default=list, verbose_name="Tamanhos Disponíveis"),
                ),
                (
                    "cores_disponiveis",
                    models.JSONField(default=list, verbose_name="Cores Disponíveis"),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Material"
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "estoque_virtual",
                    models.PositiveIntegerField(
                        default=999, verbose_name="Estoque Virtual"
                    ),
                ),
                (
                    "vendas_simuladas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Vendas Simuladas"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, verbose_name="Produto em Destaque"
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="produtos.categoria",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="fornecedores.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="produtos.tag", verbose_name="Tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["-data_cadastro"],
            },
        ),
        migrations.CreateModel(
            name="ImagemProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(upload_to="produtos/", verbose_name="Imagem"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Texto Alternativo"
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="produtos.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem do Produto",
                "verbose_name_plural": "Imagens dos Produtos",
                "ordering": ["ordem"],
            },
        ),
    ]
