# Generated by Django 5.2.3 on 2025-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrinho", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinho",
            name="cep_frete",
            field=models.CharField(
                blank=True, max_length=9, verbose_name="CEP para Frete"
            ),
        ),
        migrations.AddField(
            model_name="carrinho",
            name="valor_frete",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor do Frete",
            ),
        ),
    ]
