# Generated by Django 5.2.4 on 2025-07-25 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pedido",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmado", "Confirmado"),
                            ("processando", "Em Processamento"),
                            ("enviado", "Enviado"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                            ("devolvido", "Devolvido"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_pedido",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Pedido"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Envio"
                    ),
                ),
                (
                    "data_entrega",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Entrega"
                    ),
                ),
                (
                    "nome_cliente",
                    models.CharField(max_length=200, verbose_name="Nome do Cliente"),
                ),
                (
                    "email_cliente",
                    models.EmailField(max_length=254, verbose_name="E-mail do Cliente"),
                ),
                (
                    "telefone_cliente",
                    models.CharField(max_length=20, verbose_name="Telefone do Cliente"),
                ),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                ("endereco", models.CharField(max_length=200, verbose_name="Endereço")),
                ("numero", models.CharField(max_length=10, verbose_name="Número")),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "valor_frete",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor do Frete",
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Desconto",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("stripe", "Cartão de Crédito (Stripe)"),
                            ("mercadopago", "Mercado Pago"),
                            ("pix", "PIX"),
                            ("boleto", "Boleto"),
                        ],
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "pagamento_confirmado",
                    models.BooleanField(
                        default=False, verbose_name="Pagamento Confirmado"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ID da Transação"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "codigo_rastreamento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Código de Rastreamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-data_pedido"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_produto",
                    models.CharField(max_length=200, verbose_name="Nome do Produto"),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Unitário"
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "tamanho",
                    models.CharField(blank=True, max_length=10, verbose_name="Tamanho"),
                ),
                (
                    "cor",
                    models.CharField(blank=True, max_length=50, verbose_name="Cor"),
                ),
                (
                    "fornecedor_nome",
                    models.CharField(max_length=200, verbose_name="Nome do Fornecedor"),
                ),
                (
                    "fornecedor_email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail do Fornecedor"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens dos Pedidos",
            },
        ),
        migrations.CreateModel(
            name="StatusPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmado", "Confirmado"),
                            ("processando", "Em Processamento"),
                            ("enviado", "Enviado"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                            ("devolvido", "Devolvido"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_alteracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Alteração"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_status",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "usuario_alteracao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que Alterou",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Status",
                "verbose_name_plural": "Histórico de Status",
                "ordering": ["-data_alteracao"],
            },
        ),
    ]
