# Generated by Django 5.2.3 on 2025-08-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Tamanho recomendado: 400x400px",
                null=True,
                upload_to="perfis/",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
